table Table
	lineageTag: 30b0a26d-9f58-4b70-b28d-76cfc7ca1d92

	column Column1
		dataType: string
		lineageTag: 7adb90ff-6056-4fa4-8ace-0a99df7b9a9a
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 1bef8302-c251-48b2-ad57-96f6b725aac3
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSixOUdJRKk4BQaVYnWilFCSBYphIMVAIzi9GCCjFxgIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t])
				in
				  Source

